platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RnTestTask' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # Pods for RnTestTask
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'RnTestTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end                                                                                      
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RnTestTask-tvOS' do
  # Pods for RnTestTask-tvOS

  target 'RnTestTask-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
